# RGB WIDGET BATTERY SETTINGS
# default colors: green, yellow and red for
# high, med and low (also critical) battery level
# no color for missing peripheral
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_ONLY_PERIPHERALS=y
CONFIG_RGBLED_WIDGET_BATTERY_BLINK_MS=1000
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MISSING=0

# RGB WIDGET CONNECTION SETTINGS
# white for USB
# blue for connected BT
# cyan for advertising BT
# magenta for disconnected BT
CONFIG_RGBLED_WIDGET_CONN_SHOW_USB=y
CONFIG_RGBLED_WIDGET_CONN_COLOR_USB=7
CONFIG_RGBLED_WIDGET_CONN_COLOR_CONNECTED=4
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=6
CONFIG_RGBLED_WIDGET_CONN_COLOR_DISCONNECTED=5

# RGB WIDGET LAYER SETTINGS
# no color for layer 0
# cyan for layers 1 through 5
# red for layer 6
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=1
